image: hashicorp/terraform:light

pipelines:
  default:
    - step:
        script:
            - export VERSION=$BITBUCKET_BUILD_NUMBER
            - chmod +x ./scripts/build-image.sh
            - chmod +x ./scripts/push-image.sh
            - chmod +x ./scripts/provision-kubernetes.sh
            - chmod +x ./script/live-test.sh
            
    - parallel: # Build Docker images and push to registry in parallel.
      - step:
          services:
            - docker
          script:
            - ./scripts/build-image.sh service
            - ./scripts/push-image.sh service
      - step:
          services:
            - docker
          script:
            - ./scripts/build-image.sh web
            - ./scripts/push-image.sh web

    - step: # Provision and test cloud environment.
        script:
          - ./scripts/provision-kubernetes.sh
          - ./script/live-test.sh