image: hashicorp/terraform:light

pipelines:
  default:
    - parallel: # Build Docker images and push to registry in parallel.
      - step:
          services:
            - docker
          script:
            - export VERSION=$BITBUCKET_BUILD_NUMBER
            - chmod +x ./scripts/build-image.sh
            - ./scripts/build-image.sh service
            - chmod +x ./scripts/push-image.sh
            - ./scripts/push-image.sh service
      - step:
          services:
            - docker
          script:
            - export VERSION=$BITBUCKET_BUILD_NUMBER
            - chmod +x ./scripts/build-image.sh
            - ./scripts/build-image.sh web
            - chmod +x ./scripts/push-image.sh
            - ./scripts/push-image.sh web

    - step: # Provision and test cloud environment.
        script:
          - export VERSION=$BITBUCKET_BUILD_NUMBER
          - chmod +x ./scripts/provision-kubernetes.sh
          - ./scripts/provision-kubernetes.sh
          - chmod +x ./scripts/live-test.sh
          - ./scripts/live-test.sh