version: '3'
services:

  db:
    image: mongo
    container_name: db
    ports:
     - "27017:27017"
    restart: always
    
  service:
    image: "${DOCKER_REGISTRY}/service"
    build: 
      context: ./service
      dockerfile: Dockerfile-prod
    container_name: service
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./service/src:/usr/src/app/src:z
    ports:
     - "8080:80"
    environment:
     - PORT=80
     - DBHOST=mongodb://db:27017
     - NODE_ENV=development
    depends_on:
     - db
    restart: always

  web:
    image: "${DOCKER_REGISTRY}/web"
    build: 
      context: ./web
      dockerfile: Dockerfile-prod
    container_name: web
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./web/src:/usr/src/app/src:z
    ports:
     - "80:80"
    environment:
     - PORT=80
     - NODE_ENV=development
    depends_on:
     - service
    restart: always

