version: '3'
services:

  db:
    image: mongo
    container_name: db
    ports:
     - "4002:27017"
    restart: always

  db-fixture:
    image: db-fixture
    build: ./db-fixture
    container_name: db-fixture
    depends_on:
      - db

  service:
    image: service
    build:
      context: ./service
      dockerfile: Dockerfile-dev
    container_name: service
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./service/src:/usr/src/app/src:z
    ports:
     - "4001:80"
    environment:
     - PORT=80
     - DBHOST=mongodb://db:27017
     - NODE_ENV=development
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
     - OTEL_RESOURCE_ATTRIBUTES=service.name=service
    depends_on:
     - db
    restart: always

  web:
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    container_name: web
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./web/src:/usr/src/app/src:z
    ports:
     - "4000:80"
    environment:
     - PORT=80
     - NODE_ENV=development
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
     - OTEL_RESOURCE_ATTRIBUTES=service.name=web
    depends_on:
     - service
    restart: always


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.40.0
    container_name: otel-collector
    environment:
      - LIGHTSTEP_ACCESS_TOKEN=z4B1D8HEiaGjskPh1pJCz4pC0kTu3TVdTsqeOfr625gVpmxF61ZdsSnkr4ROKt6hbhxGPyHJlySL0U0gu7QehELpplfrSxWawCgYVhpm
    ports:
      # This is default port for GRPC protocol
      - 4317:4317
#      - 55678:55678
      # This is default port for zpages debugging
      - 55679:55679
    volumes:
    #  - /path/to/ssl/certificate:/etc/ssl/certs/ca-certificates.crt
    #  - /path/to/folder/with/collector-config.yaml:/etc/otl/config.yaml
    #  - /Users/dimitris.finas/git/lightstep/collector/conf:/etc/otel
      - ./otel-collector/conf:/etc/otel
      # for otel/opentelemetry-collector-contrib:0.47.0 and above
      #- ./otel-collector/conf:/etc/otelcol-contrib/

  jaeger-server:
    image: jaegertracing/all-in-one:1.30
    container_name: jaeger
    ports:
      - 14250:14250
      - 16686:16686

#  zipkin-server:
#    image: openzipkin/zipkin
#    container_name: zipkin-server
#    mem_limit: 512M
#    environment:
#      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
#    ports:
#      - 9412:9411
