version: '3'
services:

  db:
    image: mongo
    container_name: db
    ports:
     - "4002:27017"
    restart: always

  db-fixture:
    image: db-fixture
    build: ./db-fixture
    container_name: db-fixture
    depends_on:
      - db

  users:
    image: users
    build:
      context: ./users
      dockerfile: Dockerfile-dev
    container_name: users
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./users/src:/usr/src/app/src:z
     - ./opentelemetry/src/instrumentation.js:/usr/src/app/src/instrumentation.js:z
    ports:
     - "4001:80"
    environment:
     - PORT=80
     - DBHOST=mongodb://db:27017
     - NODE_ENV=development
     - OTEL_RESOURCE_ATTRIBUTES=service.name=users-service,service.version=2.0.0
    depends_on:
     - db
    restart: always

  web:
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    container_name: web
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./web/src:/usr/src/app/src:z
     - ./opentelemetry/src/instrumentation.js:/usr/src/app/src/instrumentation.js:z
    ports:
     - "4000:80"
    environment:
     - PORT=80
     - NODE_ENV=development
     - OTEL_RESOURCE_ATTRIBUTES=service.name=web-service,service.version=2.0.0
    depends_on:
     - users
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.92.0
    container_name: otel-collector
    ports:
      # This is default port for listening to GRPC protocol
      - 4317:4317
      # This is default port for listening to HTTP protocol
      - 4318:4318
    volumes:
      # Path to the collector config file
      - ./opentelemetry/conf:/etc/otelcol-contrib/

