receivers:
  # Receiver to collect trace, metrics and logs from grpc and http protocols
  # Default is port 4317 for grpc and 4318 for http
  otlp:
    protocols:
      grpc:
      http:

  # Receiver to scrape metrics from Docker in Prometheus format
  prometheus/docker:
    config:
      scrape_configs:
        - job_name: docker-otel-eg
          static_configs:
            - targets: ["host.docker.internal:9100"]


processors:
  # Accepts spans, metrics, or logs and places them into batches
  # to better compress the data and reduce the number of outgoing connections
  batch:

exporters:
  # Exports data to the console
  debug:
    verbosity: detailed

  # Exports data to Cloud Observability
  otlp/lightstep:
    endpoint: ingest.lightstep.com:443
    headers:
      "lightstep-access-token": "{LIGHTSTEP_ACCESS_TOKEN}"
    tls:
      insecure: false
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/lightstep]
    metrics:
      receivers: [otlp, prometheus/docker]
      processors: [batch]
      exporters: [debug, otlp/lightstep]

